
["Misc Options"]
	# 
	#-----------------------------------------------------
	#
	# If true, the Enderdragon will spawn at world origin in the
	# World Blender dimension and can respawn if you put back the
	# End Crystals on the podiums. Once killed, the podium's portal 
	# will take you to the End where you can battle the End's Enderdragon. 
	# 
	# And yes, you can respawn the EnderDragon by placing 4 End Crystals 
	# on the edges of the Bedrock Podium. 
	# 
	# If set to false, the Enderdragon will not spawn.
	# NOTE: Once the Enderdragon is spawned, changing this to false will not despawn the Enderdragon. Also, this option will not
	# work in the World Blender Worldtype due to how fight managers are 
	# set up. It will only work for the dimension. 
	#
	spawnEnderDragon = true
	# 
	#-----------------------------------------------------
	#
	# The size of the different kinds of surfaces. Higher numbers means
	# each surface will be larger but might make some surfaces harder to find. Lower numbers means the surfaces are smaller but could become too chaotic or small for some features to spawn on.
	#
	#Range: 1.0 ~ 100000.0
	surfaceScale = 240.0
	# 
	#-----------------------------------------------------
	#
	# If true, carvers (mainly vanilla caves and ravines) can now carve
	# out Netherrack, End Stone, and some modded blocks as well.
	# 
	# If turned off, you might see Vanilla caves and stuff gets cutoff 
	# by a wall of End Stone, Netherrack, or modded blocks. 
	#
	carversCanCarveMoreBlocks = true

["Optimization Options"]
	# 
	#-----------------------------------------------------
	#
	# This will also place Terracotta next to fluids to try and prevent.
	# them from floating and then flowing downward like crazy.
	# 
	# It isn't perfect but it does do mostly a good job with how
	# messy and chaotic having all features and carvers together is.
	#
	containFloatingLiquids = true
	# 
	#-----------------------------------------------------
	#
	# Will try its best to place Terracotta blocks under all floating
	# fallable blocks to prevent lag when the blocks begins to fall.
	#
	preventFallingBlocks = true
	# 
	#-----------------------------------------------------
	#
	# Will place Obsidian to separate lava tagged fluids 
	# from water tagged fluids underground.
	#
	preventLavaTouchingWater = true

